#!/usr/bin/env python3
"""Generate one end-to-end dark/spectral-siren closure data set.

This is deliberately a *bridge around*, not a rewrite of, the frozen legacy
mock generator.  The scientific DAG is executed by the pinned legacy script

    darksirens/scripts/mock_dark_sirens/generate_mock_data.py

at commit c042527238bd71421b792936bc48c3b815b90d6d.  This wrapper then only
changes the serialization surface needed by the frozen ``darksirens-core``:

* complete galaxy catalog (raw truth, from legacy);
* incomplete observed catalog (raw + pixelated, from legacy);
* a pixelated COMPLETE catalog at true z for the machinery-closure gate;
* GW posterior samples in current gwcat2 default format (gwcat-pe-2.0);
* detected selection injections in current gwcat2 default format
  (gwcat-selection-2.0);
* one manifest consumed by the H100 spectral- and dark-siren benchmark scripts.

Why gwcat 2.0 rather than 2.1?
-----------------------------
The current gwcat package still maps the public ``gwcat2`` format to 2.0; 2.1
is an opt-in provenance contract built around production ingest/export metadata.
This mock is a direct-density generator and must not fabricate production prior,
campaign, or event-selection provenance merely to fill a 2.1 contract.  The
2.0 pair is strict-validated by the *latest installed gwcat* before this script
returns, and darksirens-core natively accepts both 2.0 and 2.1.

The legacy generator supplies the important closure properties unchanged:
hosts are drawn from the complete catalog before EM incompleteness, source-rate
evolution is applied as (1+z)^(gamma-1), detection thresholds the recorded noisy
SNR, PE conditions on that same recorded measurement, and the selection set uses
the same measurement family and threshold.

Typical H100 validation data set
--------------------------------
Assuming sibling checkouts ``darksirens``, ``darksirens-core``, ``gwcat`` and
``darksirens-rebuild``::

    python examples/generate_mock_dark_siren_closure.py \
        --outdir data/mock_closure \
        --nobs 100 --nsamp 1024 --nselection 500000 \
        --n0 1e-4 --zmax 0.30 --nside 16 \
        --survey-z50 0.18 --survey-width 0.05 \
        --survey-magnitude-limit 21.0 \
        --proposal population+uniform --snr-ref 10

Then run both gates on exactly the same GW realization::

    python examples/spectral_sirens_gwcat_h100.py --mock-dir data/mock_closure ...
    python examples/dark_sirens_gwcat_h100.py --mock-dir data/mock_closure \
        --catalog-mode complete ...
    python examples/dark_sirens_gwcat_h100.py --mock-dir data/mock_closure \
        --catalog-mode incomplete ...
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
from typing import Any

import h5py
import numpy as np

LEGACY_SHA = "c042527238bd71421b792936bc48c3b815b90d6d"
LEGACY_RELATIVE_GENERATOR = Path("scripts/mock_dark_sirens/generate_mock_data.py")


def _default_legacy_root() -> Path:
    # .../darksirens-rebuild/examples/file.py -> parent containing sibling repos
    return Path(__file__).resolve().parents[2] / "darksirens"


def _git_sha(repo: Path) -> str:
    try:
        return subprocess.check_output(
            ["git", "-C", str(repo), "rev-parse", "HEAD"], text=True
        ).strip()
    except Exception as exc:
        raise RuntimeError(f"cannot resolve git SHA for {repo}") from exc


def _copy_attrs(src: h5py.File, dst: h5py.File) -> None:
    for key, value in src.attrs.items():
        dst.attrs[key] = value


def _copy_root_datasets(src: h5py.File, dst: h5py.File) -> None:
    for key, obj in src.items():
        if isinstance(obj, h5py.Dataset):
            dst.create_dataset(key, data=np.asarray(obj), compression="gzip")


def _derived_redshift(handle: h5py.File) -> np.ndarray:
    if "redshift" in handle:
        return np.asarray(handle["redshift"], dtype=np.float64)
    m1det = np.asarray(handle["m1det"], dtype=np.float64)
    m1src = np.asarray(handle["m1src"], dtype=np.float64)
    return m1det / m1src - 1.0


def _require_positive(name: str, values: np.ndarray) -> None:
    values = np.asarray(values)
    if not np.all(np.isfinite(values)):
        raise RuntimeError(f"{name} contains non-finite values")
    if np.any(values <= 0.0):
        nbad = int(np.sum(values <= 0.0))
        raise RuntimeError(f"{name} contains {nbad} non-positive values")


def _convert_pe_to_gwcat2(src_path: Path, dst_path: Path) -> None:
    """Bridge the legacy mock PE file to the current gwcat2 default schema.

    No density is recomputed.  ``p_pe`` remains the exact direct mock PE density
    generated by legacy.  The extra v2 datasets/attrs are declarative/structural.
    """
    with h5py.File(src_path, "r") as src:
        _require_positive("p_pe", np.asarray(src["p_pe"]))
        redshift = _derived_redshift(src)
        q = np.asarray(src["m2det"], float) / np.asarray(src["m1det"], float)

        with h5py.File(dst_path, "w") as dst:
            _copy_attrs(src, dst)
            _copy_root_datasets(src, dst)
            if "redshift" not in dst:
                dst.create_dataset("redshift", data=redshift, compression="gzip")
            if "q" not in dst:
                dst.create_dataset("q", data=q, compression="gzip")

            dst.attrs["format_version"] = "gwcat-pe-2.0"
            dst.attrs["spin_basis"] = "chieff"
            dst.attrs["spin_prior_mode"] = "include"
            dst.attrs["chi_eff_prior_applied_to_p_pe"] = True
            dst.attrs["mock_direct_density"] = True
            dst.attrs["mock_density_note"] = (
                "Direct all-observable-v3 mock PE density from frozen legacy; "
                "not a production gwcat ingest/export prior declaration."
            )
            dst.attrs["bridge_legacy_sha"] = LEGACY_SHA
            nobs = int(dst.attrs["nobs"])
            names = [f"MOCK{idx:04d}" for idx in range(nobs)]
            dst.attrs["event_names"] = np.asarray(names, dtype="S")

            # Preserve truth/rejected diagnostic groups without making them part
            # of the inference contract.
            for group_name in ("truth", "rejected"):
                if group_name in src and group_name not in dst:
                    src.copy(group_name, dst)


def _convert_selection_to_gwcat2(src_path: Path, dst_path: Path) -> None:
    """Bridge the legacy direct-density selection file to gwcat-selection-2.0."""
    with h5py.File(src_path, "r") as src:
        _require_positive("pdraw", np.asarray(src["pdraw"]))
        redshift = _derived_redshift(src)
        q = np.asarray(src["m2det"], float) / np.asarray(src["m1det"], float)

        with h5py.File(dst_path, "w") as dst:
            _copy_attrs(src, dst)
            _copy_root_datasets(src, dst)
            if "redshift" not in dst:
                dst.create_dataset("redshift", data=redshift, compression="gzip")
            if "q" not in dst:
                dst.create_dataset("q", data=q, compression="gzip")

            dst.attrs["format_version"] = "gwcat-selection-2.0"
            dst.attrs["spin_basis"] = "chieff"
            # Legacy already stores pdraw in the final chieff density; core must
            # therefore not multiply another chi_eff prior into it.
            dst.attrs["chi_eff_swap_applied"] = True
            dst.attrs.setdefault("chi_eff_amax", 0.99)

            # Current gwcat's v2 validator requires campaign spin-provenance
            # fields.  For this synthetic direct-coordinate campaign these mean
            # "the final chieff density is valid on the canonical support", not
            # that a hidden production component-spin file was ingested.
            dst.attrs["injected_spin_format"] = np.asarray(
                ["mock_direct_chieff"], dtype="S"
            )
            dst.attrs["injected_spin_amax_detected"] = np.asarray([0.99])
            dst.attrs["injected_spin_uniform_isotropic"] = np.asarray([True])
            dst.attrs["spin_basis_assumption_violations"] = "[]"
            dst.attrs["mock_direct_density"] = True
            dst.attrs["mock_density_note"] = (
                "Direct chieff proposal density generated by frozen legacy; "
                "campaign spin-provenance attrs are synthetic compatibility "
                "metadata, not production injection-release provenance."
            )
            dst.attrs["bridge_legacy_sha"] = LEGACY_SHA


def _pixelate_complete_catalog(
    raw_complete: Path,
    out_path: Path,
    *,
    nside: int,
    z_depth: float,
    dz: float,
) -> dict[str, int]:
    """Write the core catalog contract for every galaxy at its TRUE redshift."""
    try:
        import healpy as hp
    except ModuleNotFoundError as exc:
        raise ModuleNotFoundError(
            "healpy is required by the legacy mock/pixelization validation example"
        ) from exc

    with h5py.File(raw_complete, "r") as src:
        z = np.asarray(src["z"], dtype=np.float64)
        ra = np.asarray(src["ra"], dtype=np.float64)
        dec = np.asarray(src["dec"], dtype=np.float64)

    pix = hp.ang2pix(nside, np.pi / 2.0 - dec, ra, nest=False)
    npix = hp.nside2npix(nside)
    order = np.argsort(pix, kind="stable")
    pix_s = pix[order]
    z_s = z[order]
    counts = np.bincount(pix_s, minlength=npix).astype(np.int32)
    maxg = max(1, int(counts.max()))

    zgals = np.full((npix, maxg), 100.0, dtype=np.float64)
    dzgals = np.ones((npix, maxg), dtype=np.float64)
    wgals = np.zeros((npix, maxg), dtype=np.float64)
    starts = np.concatenate(([0], np.cumsum(counts)[:-1]))
    for p in np.flatnonzero(counts):
        start = int(starts[p])
        count = int(counts[p])
        zgals[p, :count] = z_s[start : start + count]
        dzgals[p, :count] = float(dz)
        wgals[p, :count] = 1.0

    with h5py.File(out_path, "w") as dst:
        dst.attrs["nside"] = int(nside)
        dst.attrs["z_depth"] = float(z_depth)
        dst.attrs["mock_data"] = True
        dst.attrs["catalog_role"] = "complete_true_z_closure_gate"
        dst.create_dataset("zgals", data=zgals, compression="gzip")
        dst.create_dataset("dzgals", data=dzgals, compression="gzip")
        dst.create_dataset("wgals", data=wgals, compression="gzip")
        dst.create_dataset("ngals", data=counts, compression="gzip")

    return {"n_galaxies": int(counts.sum()), "max_galaxies_per_pixel": maxg}


def _copy_incomplete_catalog(src: Path, dst: Path, *, z_depth: float) -> dict[str, int]:
    shutil.copy2(src, dst)
    with h5py.File(dst, "r+") as handle:
        handle.attrs["z_depth"] = float(z_depth)
        handle.attrs["catalog_role"] = "observed_incomplete_catalog"
        n = int(np.asarray(handle["ngals"]).sum())
        maxg = int(np.asarray(handle["ngals"]).max())
    return {"n_galaxies": n, "max_galaxies_per_pixel": maxg}


def _latest_gwcat_validate(pe: Path, selection: Path) -> dict[str, Any]:
    try:
        import gwcat
    except ModuleNotFoundError as exc:
        raise ModuleNotFoundError(
            "latest gwcat must be installed to validate the bridged v2 products"
        ) from exc
    result = gwcat.validate_export(str(pe), str(selection), strict=True)
    return {str(k): bool(v) for k, v in result.items()}


def _legacy_command(args: argparse.Namespace, legacy_out: Path) -> list[str]:
    script = args.legacy_root / LEGACY_RELATIVE_GENERATOR
    cmd = [
        sys.executable,
        str(script),
        "--outdir", str(legacy_out),
        "--seed", str(args.seed),
        "--nobs", str(args.nobs),
        "--nsamp", str(args.nsamp),
        "--nselection", str(args.nselection),
        "--nbatches", str(args.nbatches),
        "--proposal", args.proposal,
        "--nside", str(args.nside),
        "--zmax", str(args.zmax),
        "--H0", str(args.H0),
        "--Om0", str(args.Om0),
        "--w0", str(args.w0),
        "--wa", str(args.wa),
        "--gamma", str(args.gamma),
        "--snr-threshold", str(args.snr_threshold),
        "--snr-ref", str(args.snr_ref),
        "--survey-z50", str(args.survey_z50),
        "--survey-width", str(args.survey_width),
        "--survey-magnitude-limit", str(args.survey_magnitude_limit),
        "--survey-z-hard-max", str(args.zmax),
        "--verbose",
    ]
    if args.n_galaxies is None:
        cmd += ["--n0", str(args.n0)]
    else:
        cmd += ["--n-galaxies", str(args.n_galaxies)]
    return cmd


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--legacy-root", type=Path, default=_default_legacy_root())
    p.add_argument("--outdir", type=Path, default=Path("data/mock_closure"))
    p.add_argument("--seed", type=int, default=1234)
    density = p.add_mutually_exclusive_group()
    density.add_argument("--n0", type=float, default=1.0e-4)
    density.add_argument("--n-galaxies", type=int, default=None)
    p.add_argument("--nobs", type=int, default=100)
    p.add_argument("--nsamp", type=int, default=1024)
    p.add_argument("--nselection", type=int, default=500_000)
    p.add_argument("--nbatches", type=int, default=1)
    p.add_argument(
        "--proposal",
        choices=("population", "uniform", "population+uniform"),
        default="population+uniform",
    )
    p.add_argument("--nside", type=int, default=16)
    p.add_argument("--zmax", type=float, default=0.30)
    p.add_argument("--H0", type=float, default=67.74)
    p.add_argument("--Om0", type=float, default=0.3075)
    p.add_argument("--w0", type=float, default=-1.0)
    p.add_argument("--wa", type=float, default=0.0)
    p.add_argument("--gamma", type=float, default=2.5)
    p.add_argument("--snr-threshold", type=float, default=8.0)
    p.add_argument("--snr-ref", type=float, default=10.0)
    p.add_argument("--survey-z50", type=float, default=0.18)
    p.add_argument("--survey-width", type=float, default=0.05)
    p.add_argument("--survey-magnitude-limit", type=float, default=21.0)
    p.add_argument("--complete-dz", type=float, default=0.003)
    p.add_argument(
        "--keep-legacy-products",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Keep the original legacy products under OUTDIR/legacy.",
    )
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    args.legacy_root = args.legacy_root.expanduser().resolve()
    out = args.outdir.expanduser().resolve()
    out.mkdir(parents=True, exist_ok=True)
    legacy_out = out / "legacy"
    if legacy_out.exists():
        shutil.rmtree(legacy_out)
    legacy_out.mkdir(parents=True)

    script = args.legacy_root / LEGACY_RELATIVE_GENERATOR
    if not script.is_file():
        raise FileNotFoundError(
            f"frozen legacy generator not found at {script}; pass --legacy-root"
        )
    observed_sha = _git_sha(args.legacy_root)
    if observed_sha != LEGACY_SHA:
        raise RuntimeError(
            "legacy checkout is not the frozen reconstruction oracle: "
            f"expected {LEGACY_SHA}, got {observed_sha}"
        )

    print(f"[legacy] {args.legacy_root} @ {observed_sha}")
    cmd = _legacy_command(args, legacy_out)
    print("[legacy] " + " ".join(cmd))
    env = dict(os.environ)
    env["PYTHONPATH"] = str(args.legacy_root) + (
        os.pathsep + env["PYTHONPATH"] if env.get("PYTHONPATH") else ""
    )
    subprocess.run(cmd, check=True, env=env, cwd=args.legacy_root)

    legacy_pe = legacy_out / "mock_gw_events.h5"
    legacy_sel = legacy_out / "mock_gw_selection.h5"
    legacy_complete = legacy_out / "mock_galaxy_catalog_complete.h5"
    legacy_incomplete = legacy_out / f"catalog_pixelated_nside_{args.nside}.h5"
    for required in (legacy_pe, legacy_sel, legacy_complete, legacy_incomplete):
        if not required.is_file():
            raise RuntimeError(f"legacy generator did not produce {required}")

    pe = out / "gw_events.h5"
    selection = out / "gw_selection.h5"
    catalog_complete = out / "catalog_complete.h5"
    catalog_incomplete = out / "catalog_incomplete.h5"

    _convert_pe_to_gwcat2(legacy_pe, pe)
    _convert_selection_to_gwcat2(legacy_sel, selection)
    complete_stats = _pixelate_complete_catalog(
        legacy_complete,
        catalog_complete,
        nside=args.nside,
        z_depth=args.zmax,
        dz=args.complete_dz,
    )
    incomplete_stats = _copy_incomplete_catalog(
        legacy_incomplete, catalog_incomplete, z_depth=args.zmax
    )

    print("[gwcat] strict-validating mock PE/selection v2 pair")
    validation = _latest_gwcat_validate(pe, selection)
    if not all(validation.values()):
        failed = [k for k, v in validation.items() if not v]
        raise RuntimeError(f"gwcat validation returned failed checks: {failed}")

    with h5py.File(pe, "r") as f:
        nobs = int(f.attrs["nobs"])
        nsamp = int(f.attrs["nsamp"])
    with h5py.File(selection, "r") as f:
        ndraw = int(f.attrs["ndraw"])
        ndet = int(len(f["pdraw"]))

    manifest = {
        "schema": "darksirens-rebuild-mock-closure-1",
        "generator": {
            "legacy_sha": LEGACY_SHA,
            "legacy_root": str(args.legacy_root),
            "legacy_script": str(LEGACY_RELATIVE_GENERATOR),
            "serialization": "synthetic direct-density bridge to gwcat2 default (2.0)",
        },
        "files": {
            "gw_events": pe.name,
            "gw_selection": selection.name,
            "catalog_complete": catalog_complete.name,
            "catalog_incomplete": catalog_incomplete.name,
            "legacy_dir": "legacy" if args.keep_legacy_products else None,
        },
        "truth": {
            "H0": args.H0,
            "Om0": args.Om0,
            "w0": args.w0,
            "wa": args.wa,
            "population": "powerlaw+peak",
            "gamma": args.gamma,
            "n0_requested": args.n0 if args.n_galaxies is None else None,
            "n_galaxies_requested": args.n_galaxies,
            "zmax": args.zmax,
            "snr_threshold": args.snr_threshold,
            "snr_ref": args.snr_ref,
            "survey_z50": args.survey_z50,
            "survey_width": args.survey_width,
            "survey_magnitude_limit": args.survey_magnitude_limit,
        },
        "sizes": {
            "n_events": nobs,
            "nsamp": nsamp,
            "n_pe_rows": nobs * nsamp,
            "ndraw": ndraw,
            "n_detected_injections": ndet,
            "complete_catalog": complete_stats,
            "incomplete_catalog": incomplete_stats,
            "observed_fraction": (
                incomplete_stats["n_galaxies"] / complete_stats["n_galaxies"]
            ),
        },
        "gwcat_validation": validation,
        "notes": [
            "Hosts are drawn from the complete catalog before EM incompleteness.",
            "Complete catalog uses true z; incomplete catalog uses legacy realised photo-z.",
            "The v2 bridge preserves legacy p_pe/pdraw without recomputation.",
            "Mock spin provenance compatibility attrs are not production injection-release provenance.",
        ],
    }
    manifest_path = out / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")

    if not args.keep_legacy_products:
        shutil.rmtree(legacy_out)

    print("\nGenerated closure data set")
    print(f"  manifest:           {manifest_path}")
    print(f"  GW PE:              {pe}")
    print(f"  GW selection:       {selection}")
    print(f"  complete catalog:   {catalog_complete}")
    print(f"  incomplete catalog: {catalog_incomplete}")
    print(
        "  galaxies:           "
        f"complete={complete_stats['n_galaxies']:,}, "
        f"observed={incomplete_stats['n_galaxies']:,}, "
        f"fraction={manifest['sizes']['observed_fraction']:.3f}"
    )
    print(f"  GW:                 {nobs} events x {nsamp} PE samples")
    print(f"  selection:          {ndet:,} detected / {ndraw:,} proposed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
